sudo: required
services:
  - docker

before_install:
  - docker build -t frontend -f ./frontend/Dockerfile.dev ./frontend
  - docker build -t backend -f ./backend/Dockerfile.dev ./backend

script:
  - docker run -e CI=true frontend npm test
  - docker-compose run api python manage.py test