sudo: required
services:
  - docker

before_install:
  - docker build -t frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true frontend npm test
  - docker-compose run api ./wait-for-postgres.sh db:5432 -- python manage.py test