sudo: required
services:
  - docker

before_install:
  - docker build -t frontend -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true frontend npm run lint
  - docker run -e CI=true frontend npm test

after_success:
  - docker build -t jiaqiwang118/template-frontend ./frontend
  - docker build -t jiaqiwang118/template-backend ./backend
  - docker build -t jiaqiwang118/template-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jiaqiwang118/template-frontend
  - docker push jiaqiwang118/template-backend
  - docker push jiaqiwang118/template-nginx

deploy:
  provider: elasticbeanstalk
  region: $AWS_REGION
  app: $APP_NAME
  env: $ENV_NAME
  bucket_name: $S3_BUCKET_NAME
  bucket_path: $APP_NAME
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY