version: "3"
services:
  api:
    image: "jiaqiwang118/template-backend"
    mem_limit: 128m
    hostname: api
    command: sh -c "python manage.py wait_for_db &&
                    python manage.py migrate &&
                    ./manage.py collectstatic --noinput &&
                    gunicorn backend.wsgi --bind 0.0.0.0:8000"
    environment:
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=1
  frontend:
    image: "jiaqiwang118/template-frontend"
    mem_limit: 128m
    hostname: frontend
  nginx:
    image: "jiaqiwang118/template-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"